name: gym_tracker_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  fluttertoast: ^8.0.8
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.14.1
  cloud_firestore: ^5.6.5
  cloud_firestore_web: ^4.4.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
