name: grindstone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  fluttertoast: ^8.2.12
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.14.1
  cloud_firestore: ^5.6.5
  cloud_firestore_web: ^4.4.5
  http: ^0.13.3
  uuid: ^3.0.4
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.9
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/logo/gGreen.svg
    - assets/logo/gPurple.svg
    - assets/logo/gGreen.png
    - assets/logo/gPurple.png
