// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOEKg3nIjw1wPZo4GMWqZff3vAt6vKdQ',
    appId: '1:128236045719:web:ed612e5645e95a0453b0d2',
    messagingSenderId: '128236045719',
    projectId: 'gym-tracker-flutter',
    authDomain: 'gym-tracker-flutter.firebaseapp.com',
    storageBucket: 'gym-tracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlJB0zuvO9yZYi4cob3rIJHQv2-XzBi0',
    appId: '1:128236045719:android:1eb3e174cd2442ca53b0d2',
    messagingSenderId: '128236045719',
    projectId: 'gym-tracker-flutter',
    storageBucket: 'gym-tracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBsnv9_JsrMQyuoRTTCpnwksBH_09ROE',
    appId: '1:128236045719:ios:aec538553dcf65a553b0d2',
    messagingSenderId: '128236045719',
    projectId: 'gym-tracker-flutter',
    storageBucket: 'gym-tracker-flutter.firebasestorage.app',
    iosBundleId: 'com.example.gymTrackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBsnv9_JsrMQyuoRTTCpnwksBH_09ROE',
    appId: '1:128236045719:ios:aec538553dcf65a553b0d2',
    messagingSenderId: '128236045719',
    projectId: 'gym-tracker-flutter',
    storageBucket: 'gym-tracker-flutter.firebasestorage.app',
    iosBundleId: 'com.example.gymTrackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJOEKg3nIjw1wPZo4GMWqZff3vAt6vKdQ',
    appId: '1:128236045719:web:22a6803a4ff35e0753b0d2',
    messagingSenderId: '128236045719',
    projectId: 'gym-tracker-flutter',
    authDomain: 'gym-tracker-flutter.firebaseapp.com',
    storageBucket: 'gym-tracker-flutter.firebasestorage.app',
  );
}
